# Generated by Django 6.0 on 2025-12-06 23:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CleanImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Np. Fiat Ducato bok", max_length=100
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="clean_images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["bmp", "jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("aspect_ratio", models.FloatField(db_index=True, default=0.0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScanRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="scans_input/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["bmp", "jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Oczekuje"),
                            ("processing", "Przetwarzanie"),
                            ("completed", "Zakończono"),
                            ("error", "Błąd"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "result_image",
                    models.ImageField(blank=True, null=True, upload_to="scans_output/"),
                ),
                (
                    "anomalies_found",
                    models.IntegerField(
                        default=0, help_text="Liczba wykrytych anomalii"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matched_clean_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scanner.cleanimage",
                    ),
                ),
            ],
        ),
    ]
