# Generated by Django 6.0 on 2025-12-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cleanimage",
            name="aspect_ratio",
            field=models.FloatField(db_index=True, default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name="scanrequest",
            name="anomalies_found",
            field=models.IntegerField(default=0),
        ),
    ]
