# Generated by Django 6.0 on 2025-12-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0002_alter_cleanimage_aspect_ratio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanrequest",
            name="confirmed_label",
            field=models.CharField(
                choices=[
                    ("unknown", "Nieokreślone"),
                    ("clean", "Czyste (Bez anomalii)"),
                    ("dirty", "Brudne (Przemyt/Anomalia)"),
                ],
                default="unknown",
                help_text="Czy użytkownik potwierdził, że to przemyt?",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scanrequest",
            name="user_comments",
            field=models.TextField(
                blank=True, help_text="Uwagi użytkownika do skanu", null=True
            ),
        ),
    ]
