# Generated by Django 6.0 on 2025-12-07 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0003_scanrequest_confirmed_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanrequest",
            name="detection_data",
            field=models.JSONField(
                blank=True, help_text="Współrzędne ramek i wyniki pewności", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cleanimage",
            name="image",
            field=models.ImageField(
                upload_to="clean_images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["bmp"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="scanrequest",
            name="image",
            field=models.ImageField(
                upload_to="scans_input/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["bmp"]
                    )
                ],
            ),
        ),
    ]
