# Generated by Django 6.0 on 2025-12-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0004_scanrequest_detection_data_alter_cleanimage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanrequest",
            name="difference_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="scans_diffs/",
                verbose_name="Obraz Różnicowy (Morfologia)",
            ),
        ),
    ]
